# for available inventory fields see:
# https://www.zabbix.com/documentation/4.4/manual/api/reference/host/object#host_inventory
# 4.4 is the minimum version supported here, so for now use the specification for that.

# This can be included in two ways:
# 1. by the host itself during host setup
# 2. by localhost or a zabbix server during a generic configuration run
#
# Case 1 is relatively easy, inventory can be populated by what ansible has
# discovered. The second case is a bit more complicated, as we don't want
# to overwrite items discovered in a separate run.
#
# Check if inventory_hostname matches _zabbix_host for that kind of data changes
# to avoid overwriting.

- set_fact:
    _zd:
      os: default-os
      site_rack: "{{network_nodes[_zabbix_host].rack|default('')}}"

- set_fact:
    _zinventory:
      hw_arch: "{{ansible_architecture}}"
      os: "{{ansible_distribution}} {{ansible_distribution_version}}"
      os_short: "{{ansible_distribution}}"
      os_full: "{{ansible_distribution}} {{ansible_distribution_version}} {{ansible_kernel}}"
      software_full: "python: {{ansible_python_version}} apparmor: {{ansible_apparmor.status}} selinux: {{ansible_selinux.status}}"
  when: inventory_hostname == _zabbix_host

- set_fact:
    _zd: "{{ _zd | combine (_zinventory)}}"

- set_fact:
    _zvirt:
      chassis: "{{ansible_virtualization_type}} on {{network_nodes[inventory_hostname].machine}}"
      type: "{{ansible_virtualization_type}}"
  when: >
    inventory_hostname == _zabbix_host and
    ansible_virtualization_role == 'guest'

- set_fact:
    _zd: "{{ _zd | combine (_zvirt)}}"
  when: >
    inventory_hostname == _zabbix_host and
    ansible_virtualization_role == 'guest'

# ansible_product_uuid
# ansible_product_version
# ansible_system: Linux
- set_fact:
    _zhw:
      hardware_full: "cpus: {{ansible_processor_count}} cores: {{ansible_processor_cores}} threads: {{ansible_processor_vcpus}} bios: {{ansible_bios_version}} bios date: {{ansible_bios_date}}"
      chassis: "{{ansible_product_name}}"
      vendor: "{{ansible_system_vendor}}"
      serialno_a: "{{ansible_product_serial}}"
      type: "{{ansible_form_factor}}"
  when: >
    ansible_virtualization_role is undefined or
    ansible_virtualization_role == 'host'

- set_fact:
    _zd: "{{ _zd | combine (_zhw)}}"
  when: >
    ansible_virtualization_role is undefined or
    ansible_virtualization_role == 'host'
- set_fact:
    _zabbix_inventory_dict: "{{_zd}}"