---
# handlers file for Zabbix Agent
- name: restart zabbix-agent
  service: name=zabbix-agent state=restarted

- name: restart firewalld
  service: name=firewalld state=restarted

- name: restart iptables
  service: name=iptables state=restarted
  tags:
    -iptables
